### PR TITLE
Add basic implementation of ssl-simulation-protocol

### PR DESCRIPTION
**Pull request by g3force**
This PR adds a basic implementation of the new [ssl-simulation-protocol](https://github.com/RoboCup-SSL/ssl-simulation-protocol).

The robot control and feedback is implemented, providing the same functionality as the internal protocol.
However
 * Details like changing the dribbling speed (not just turning off/on) are not yet implemented.
 * Controlling the robot with global velocity does not behave as one would probably expect, because the commands are simply converted to local commands.
 * I have not yet tested the wheel speed commands.

The simulation control is partially implemented:
 * The ball and robots can be placed, including a set velocity
 * Robots can be removed by turning them off and placing it outside the field
 * teleport_safely and roll for ball is not yet implemented
 * simulation_speed is not yet implemented
 * the whole config message is not yet implemented

Teams are welcome to test their software with this branch. If everything works, I suggest to merge these features and deal with the remaining ones separately.

### CODE REVIEW

**Comment by mahi97** [comment]
I think Travis CI doesn't provide unlimited free service for open-source projects anymore.
Should we consider switching to Circle CI?

**Comment by mahi97** [comment]
Not directly related to this PR, but generally for SSL competition on a simulation platform.

IMO, The best way for dealing with competition on a simulation platform is to add another node as a referee before the simulator.
In this setting, all teams' client applications connect directly to the referee node, and only the referee can talk with the simulator.

This way, we can easily limit and regulate the client's request (robot commands) and have a better synchronization for applying commands on simulation. Also, sending of responses (robot status, vision, referee commands) become unified.

But still, this question remained that where is the source of the clock ticks.

1. **Clients**: When both clients send the commands, we apply the commands and send the new perception back to clients. Grsim doesn't call step by the timer. (clients have the freedom to have dynamic calculation time (maybe limited to max number)). 

2. **Grsim**: It runs on fixed frequency as the real-world is always running whether we take any action or not. Teams command will be applied whenever they send it.

3. **Referee**: It runs on fixed frequency as the real-world is always running whether we take any action or not. Teams command will be applied on the next clock.

**Comment by g3force** [comment]
An intermediate "referee" node could indeed be a good option. I have not yet come to a final solution as of how we will do it.
We would still need to keep in mind that the simulator interface is not protected, so teams could theoretically still circumvent the "referee", if we do not add additional protection.

As of the clock ticks, I think for a tournament, it is totally fine to have it in the simulator. It sends out the vision packets, like ssl-vision would, and other components can take the timestamps to measure elapsed time. Ideally, the simulator runs in real time the whole time anyway.
For development though, it might be better for the teams to control the speed on their own and maybe even have a synchronized way with input -> output (see the Readme in the ssl-simulation-protocol repo).

I do not like how grSim is currently handling robot commands, especially the kick command. You can not just "arm" the kicker and let it kick as soon as the ball touches the dribbler. Checking if the ball is touching the dribbler is only done per command. That's at least not how TIGERs robots work and I think most teams have a light barrier or similar to detect the ball.
But that should not be too hard to change.

We might want to define/limit the frequency of robot commands. That could be something for the "referee" node, but could also be in grSim or just monitored somehow.

There is also currently the idea, to make use of gRPC, especially for the simulator control. Authorization would be possible and single commands could be send quite easily with e.g. gcurl.

**Comment by mahi97** [comment]
> We would still need to keep in mind that the simulator interface is not protected, so teams could theoretically still circumvent the "referee", if we do not add additional protection.

I completely agree, IMO running simulator and referee in isolated docker with the only limited port open for teams communication with referee can do the job, also simulator can work on localhost IP.

> As the clock ticks, I think for a tournament, it is totally fine to have it in the simulator. It sends out the vision packets as ssl-vision would, and other components can take the timestamps to measure elapsed time. Ideally, the simulator runs in real time the whole time anyway.
For development though, it might be better for the teams to control the speed on their own and maybe even have a synchronized way with input -> output (see the Readme in the ssl-simulation-protocol repo).

Got it, I like the idea.

> I do not like how grSim is currently handling robot commands, especially the kick command. You can not just "arm" the kicker and let it kick as soon as the ball touches the dribbler. Checking if the ball is touching the dribbler is only done per command. That's at least not how TIGERs robots work and I think most teams have a light barrier or similar to detect the ball.
But that should not be too hard to change.

I'm afraid I didn't understand it correctly, Do you want to set the kicker to an "arm" mode and the kicker remained in that state till you send an "un-arm"? (While the kicker is armed it can kick the ball as it touches the dribbler.)
or is your concern about the amount of time which robot doesn't kick between two commands? (~16ms) 

> We might want to define/limit the frequency of robot commands. That could be something for the "referee" node, but could also be in grSim or just monitored somehow.

Definitely necessary, I vote for using an out-of-the-box tool for monitoring even though we implement any protection still monitoring is beneficial.
I guess it's less concern in the case of using grpc.


> There is also currently the idea, to make use of gRPC, especially for the simulator control. Authorization would be possible and single commands could be send quite easily with e.g. gcurl.

I actually tried it for two other simulation competitions, and it results very well in case of performance and ease of use. But I afraid it might not be as general as protobuf itself and might limit some teams, anyway there's always room for making a wrapper with python or another well-supported language.

**Comment by g3force** [comment]
> I'm afraid I didn't understand it correctly, Do you want to set the kicker to an "arm" mode and the kicker remained in that state till you send an "un-arm"? (While the kicker is armed it can kick the ball as it touches the dribbler.)
> or is your concern about the amount of time which robot doesn't kick between two commands? (~16ms)

My concern is that the bot may not kick the ball correctly, when the ball is coming in with high speed. If the ball is coming in with 3m/s, it can move 5cm within 16ms. So chances are, that the ball will bounce off the dribbler, without being kicked. Not sure how well this is currently working in practice.

**Comment by mahi97** [comment]
OK, I got it, I'll work on it.

**Comment by g3force** [comment]
I suggest to merge this PR asap and work on the remaining points on separate PRs.

**Review by mahi97 — APPROVED** [review]

**Pull request merged**
