### PR TITLE
Feature/pluggable robot

### PR DESCRIPTION
**Pull request by PhiBabin**
# Add team plugin support
Team ULtron is working on RoboCup Arena. A platform to have different RoboCup SSL team's AI play against each other in a simulated environment. The goal is to accelerate development by testing AI against other AI without having to wait for a real life competition. The requirements of RoboCup Arena are that two team with different AI must be able to play against each other in grSim, without needing to recompile grSim for a specific match up.
While most RoboCup team supports grSim, almost all of them actually used their own fork. These forks range from a basic setting customization to a completely rewrite of the network's packets. Since these customizations are sometime mutually exclusive, it's impossible to have one universal version of grSim that would support everyone. Thus, RoboCup Arena required the addition of plugins to grSim.

Our PR is based on #78 by ompugao, however, that PR was trying to add custom robot plugin, we are adding a team plugin. Team plugins enable a customization of both the team and its robots.

### Description of the Change
The main feature of this PR is the ability to receive and to execute custom Protobuf packets unique to each teams. Protobuf supports having multiple versions of the same message as long as the `required` field stay the same. However only a single definition of the Protobuf can be linked, thus external dynamic libraries are used to achieve multiple versions.

This PR implements team's plugin using external dynamic libraries. A team plugin is loaded by checking the `.ini` file of that particular team. A new field `CustomTeamPlugin/NameDLL` tells the name of the external library to load. A single function of the external library is loaded `create_foobar_team` (where foobar is the team's name), this function is a factory for the team's custom implementation of the `Team` abstract class. 
For an example of a working plugin [check the RoboJacket plugin](https://github.com/PhiBabin/grSim_plugin_roboJacket). To implement a new team you only have to implement two methods of the `Team` class, a `Team::create_robots` method, which enable the creating of custom robot, and a `Team::handle_cmds` method which handle the parsing and execution of the `Grsim_packets`. Most teams customizes the `Grsim_Commands` by adding additional fields. For instance, robojacket added a `triggermode` field which set the kicker to different trigger mode. Thus in the plugin, a different version of the Protobuf message is used to parse incoming commands. The behavior of `triggermode` is also implemented inside `Team::handle_cmds`. 

To review this PR I suggest first reading the #78 for the `robot.cpp` and `robot.h` part, since this remains mostly unchanged. The most important changes are in, `team.cpp`, `ConfigWidget.cpp` and `sslworld.cpp`.
 
Since the addition of Boost DLL as dependencies was a problem in #78, I added a cmake flag to disable the importation of external libraries. So teams still using ubuntu 16.04, won't need to install a new boost version.
In this PR, I also fix a bug with the `RobotSettings`, where the two teams used the blueteam settings. 
To fix it, I took the liberty of refactoring the `Current_team` attribute.
 
I still need to write a clear documentation on how to write a plugin and upgrade grSim's README.

### Alternate Designs
 - Using reflection Protobuf behavior to achieve multiple version of a Protobuf message: An older version of a Protobuf message can access newer optional field that it normally can not have access. However this is not user friendly and makes the code hard to maintain. 
 - Using a single canonical protobuf message which works for all team. This will be hard to maintain since each team will need to add their own specific flags. We fallback to the same problem of needing to implement fork instead of using plugins. 

### Possible Drawbacks
 - If we need to change a piece of code that's now handle by the plugin, every plugin will need to be upgrade.
 - All team must have protobuf packets that are compatible with current version. Which means all `required` field must stay `required` and all field ID must remains the same. Some teams like RoboJacket will need to upgrade their protobuf message to respect this. For most teams, it's possible to create a plugin without changing their AI at all.
 - If you send a custom packet meant for Team A to grSim and you forgot to activate the plugin for Team A, you will not get any error messages. It could be solve by adding an optional field with the team name inside the `grSim_packet` Protobuf message.

### Verification Process
I tested Ultron (which works with vanillia grSim) against RoboJacket (which require a plugin). The two teams were able to play against each other.
 
### Release Notes
 - A team's configuration file (aka the `.ini` file) can now load an external DLL by specifying the field `CustomTeamPlugin/NameDLL`. This field specifies the filename stem of the external library. The library will be search in `~/.grsim/plugin` and at the path specified by the environment variable `GRSIM_PLUGIN_PATH`.
 - Add the ability to selection a team setting via the CLI. For instance,  `./grsim -b robojacket -y Parsian` will start grSim with the blue team using the `robojacket.ini` team configuration file and the yellow team using `Parsian.ini`.
 - Fix a bug were the yellow team's settings were never used, the two teams used the blue team's settings.
 - Instead of hardcoding the g++ flag for c++11, now the standard CMake command is used.
 - The external DLL plugin can be disable by passing the flag `-DENABLE_PLUGIN_WITH_EXTERNAL_DLL=ON` at cmake.

### CODE REVIEW

**Comment by mahi97** [comment]
Many thanks for your efforts and contributing.

There are many changes in your PR and I need to review them in more depth.
For make this progress more smoothly and certain please work on the travis error, to get a green light.
I also suggest to merge the current branch into a `develop` branch and after more test we move it to the `master`.

**Comment by PhiBabin** [comment]
Could you create a `develop` branch? I don't have the permissions.

**Comment by mahi97** [comment]
@PhiBabin develop branch is created!

**Comment by PhiBabin** [comment]
The Travis build for Linux works fine. The macosX build fails during the installation of the dependencies. It seems that `brew install protobuf` takes too much time to `make check`. It seems unrelated to this PR, @mahi97 did you had that problem previously?

**Comment by mahi97** [comment]
Yes, I faced this too, I tried to use the travis cache to make it faster.

For now it's not very important issue I will check it on mac personally.

**Comment by mahi97** [comment]
Testing is Needed.

**Comment by jpfeltracco** [comment]
Hi @PhiBabin 👋 . This is super interesting, thanks for considering RoboJackets use case in this new system!

I had a question though, do you have an example of this?
> Since these customizations are sometime mutually exclusive, it's impossible to have one universal version of grSim that would support everyone.

As far as RoboJackets goes, I think our addition of ball sense to grSim probably should've been merged into grSim master rather than us maintaining a fork (I would assume just about all the teams use ball sense?). We're actually really close to just relying on mainline grSim.

Are there other teams with more complicated integrations with grSim that you're worried about?

**Pull request merged**
