### PR TITLE
dribble better & add robot sensor info & auto reset when turn over (from ZJUNlict)

### PR DESCRIPTION
**Pull request by 0aqz0**
## Issues or RFC Endorsed by GrSim's Maintainers

- Robots may turn over when they have a collision
- Robots cannot dribble well
- Unable to get robots' sensors info(such as infrared, kick status)

## Description of the Change

- reset the robot that has turned over automatically
- make robots able to dribble better
- users can get robots' sensors info(infrared, flat kick, chip kick) when the info is changed through the `messages_robocup_ssl_robot_status` protobuf message

## Alternate Designs

The current version sends robots' sensor info only when the info has changed to improve the communication efficiency.

Alternately, we can send robots' sensors info whenever receiving a command.

## Possible Drawbacks

Some users may want to see the robots turn over

## Verification Process

- Manually place a robot on another's body. The robot may turn over before. But now it is reseted automatically.
-  Make a robot dribble through `grSim_Commands` protobuf message.

```c++
grsim_robots[id]->set_spinner(true);
```

You can make the robot spin around after it has dribbled the ball and it won't lose control of the ball.

- Get the robots' sensor info through `messages_robocup_ssl_robot_status` protobuf message

```c++
QByteArray datagram;
while(true){
    std::this_thread::sleep_for(std::chrono::microseconds(500));
    while(yellowReceiveSocket.hasPendingDatagrams()) {
        Robots_Status robotsPacket;
        datagram.resize(yellowReceiveSocket.pendingDatagramSize());
        yellowReceiveSocket.readDatagram(datagram.data(), datagram.size());
        robotsPacket.ParseFromArray(datagram, datagram.size());
        for (int i = 0; i < robotsPacket.robots_status_size(); ++i) {
            int id = robotsPacket.robots_status(i).robot_id();
            bool infrared = robotsPacket.robots_status(i).infrared();
            bool isFlatKick = robotsPacket.robots_status(i).flat_kick();
            bool isChipKick = robotsPacket.robots_status(i).chip_kick();
        }
    }
}
```

## Release Notes

### CODE REVIEW

**Comment by mahi97** [comment]
I believe resetting robots after fall is right action, but as you mentioned maybe, some users still want to monitor the robots turn over.
I suggest adding a checkbox in vartypes config for this feature. (The default value can be true)

**Comment by 0aqz0** [comment]
Thank you very much for your advice. I will modify it as suggested.

**Comment by mahi97** [comment]
Thanks, Great Job!

**Comment by 0aqz0** [comment]
You are welcome!

**Pull request merged**
